version: '3'
services:
  gumtree-mongo:
    container_name: gumtree-mongo
    image: mongo:4
    restart: "always"
    ports:
      - 27017:27017
    volumes:
      # TODO: how to make it system independant?
      # - "${MONGO_DATA_DIR}:/data/db"
      - ./docker/mongo/init.sh:/docker-entrypoint-initdb.d/init.sh:ro
    environment:
      MONGO_INITDB_DATABASE: gumtree
      MONGO_INITDB_ROOT_USERNAME: gumtree
      MONGO_INITDB_ROOT_PASSWORD: "${MONGODB_PASSWORD}"

  gumtree-nginx:
    container_name: gumtree-nginx
    image: "nginx:1.17"
    restart: "always"
    ports:
      - 80:80
      - 443:443
    depends_on:
      - gumtree-web
    volumes:
      - ./docker/nginx/conf.d/gumtree.nginx:/etc/nginx/sites-enabled/default:ro

  gumtree-web:
    container_name: gumtree-web
    image: jvmops/gumtree-scrapper
    restart: "always"
    expose:
      - "8080"
    environment:
      SPRING_PROFILES_ACTIVE: web
      SPRING_DATA_MONGODB_HOST: gumtree-mongo
      SPRING_DATA_MONGODB_AUTHENTICATION-DATABASE: gumtree
      SPRING_DATA_MONGODB_USERNAME: gumtree
      SPRING_DATA_MONGODB_PASSWORD: "${MONGODB_PASSWORD}"

  gumtree-scrapper:
    container_name: gumtree-scrapper
    image: jvmops/gumtree-scrapper
    restart: "no"
    depends_on:
    # TODO: make it depend on mongo
      - gumtree-web
    environment:
      SPRING_PROFILES_ACTIVE: scrapper
      SPRING_MAIN_WEB-APPLICATION-TYPE: NONE
      SPRING_DATA_MONGODB_HOST: gumtree-mongo
      SPRING_DATA_MONGODB_AUTHENTICATION-DATABASE: gumtree
      SPRING_DATA_MONGODB_USERNAME: gumtree
      SPRING_DATA_MONGODB_PASSWORD: "${MONGODB_PASSWORD}"

  gumtree-report:
    container_name: gumtree-report
    image: jvmops/gumtree-scrapper
    restart: "no"
    depends_on:
    # TODO: make it depend on mongo
      - gumtree-web
    environment:
      SPRING_PROFILES_ACTIVE: report
      SPRING_MAIN_WEB-APPLICATION-TYPE: NONE
      SPRING_MAIL_USERNAME: "${GMAIL_USERNAME}"
      SPRING_MAIL_PASSWORD: "${GMAIL_PASSWORD}"
      SPRING_DATA_MONGODB_HOST: gumtree-mongo
      SPRING_DATA_MONGODB_AUTHENTICATION-DATABASE: gumtree
      SPRING_DATA_MONGODB_USERNAME: gumtree
      SPRING_DATA_MONGODB_PASSWORD: "${MONGODB_PASSWORD}"
