version: '3.7'
services:
  gumtree-mongo:
    container_name: gumtree-mongo
    image: mongo:4
    restart: always
    ports:
      - 27017:27017
    environment:
      GUMTREE_DB_PASSWORD: "${ADMIN_PASSWORD}"
    volumes:
      - ./mongo/init.sh:/docker-entrypoint-initdb.d/init.sh:ro

  gumtree-web:
    container_name: gumtree-web
    build:
      context: .
      args:
        - buildno
        - gitcommithash
    image: jvmops/gumtree-scrapper:latest
    restart: always
    depends_on:
      - gumtree-mongo
    ports:
      - 8080:8080
    environment:
      SPRING_PROFILES_ACTIVE: web
      SPRING_DATA_MONGODB_HOST: gumtree-mongo
      SPRING_DATA_MONGODB_AUTHENTICATION-DATABASE: gumtree
      SPRING_DATA_MONGODB_USERNAME: gumtree
      SPRING_DATA_MONGODB_PASSWORD: "${ADMIN_PASSWORD}"
      # TODO: make this email dependency go away from gumtree-web (provide rest endpoint at report?)
      SPRING_MAIL_USERNAME: "${GMAIL_USERNAME}"
      SPRING_MAIL_PASSWORD: "${GMAIL_PASSWORD}"

  gumtree-scrapper:
    container_name: gumtree-scrapper
    image: jvmops/gumtree-scrapper
    restart: "no"
    depends_on:
      - gumtree-web
    environment:
      SPRING_PROFILES_ACTIVE: scrapper
      SPRING_MAIN_WEB-APPLICATION-TYPE: NONE
      SPRING_DATA_MONGODB_HOST: gumtree-mongo
      SPRING_DATA_MONGODB_AUTHENTICATION-DATABASE: gumtree
      SPRING_DATA_MONGODB_USERNAME: gumtree
      SPRING_DATA_MONGODB_PASSWORD: "${ADMIN_PASSWORD}"

  gumtree-report:
    container_name: gumtree-report
    image: jvmops/gumtree-scrapper
    restart: "no"
    depends_on:
      - gumtree-web
    environment:
      SPRING_PROFILES_ACTIVE: report
      SPRING_MAIN_WEB-APPLICATION-TYPE: NONE
      SPRING_MAIL_USERNAME: "${GMAIL_USERNAME}"
      SPRING_MAIL_PASSWORD: "${GMAIL_PASSWORD}"
      SPRING_DATA_MONGODB_HOST: gumtree-mongo
      SPRING_DATA_MONGODB_AUTHENTICATION-DATABASE: gumtree
      SPRING_DATA_MONGODB_USERNAME: gumtree
      SPRING_DATA_MONGODB_PASSWORD: "${ADMIN_PASSWORD}"
