version: '3.7'
services:
  gumtree-mongo:
    container_name: gumtree-mongo
    image: mongo:4
    restart: "no"
    ports:
      - 27017:27017
    environment:
      GUMTREE_DB_PASSWORD: "${ADMIN_PASSWORD}"
      TZ: "Europe/Warsaw"
    volumes:
      - ./mongo/init.sh:/docker-entrypoint-initdb.d/init.sh:ro
#      - /var/local/mongo:/data/db

  gumtree-web:
    container_name: gumtree-web
    build:
      context: .
      args:
        - buildno
        - gitcommithash
    image: jvmops/gumtree-scraper
    restart: "no"
    depends_on:
      - gumtree-mongo
    ports:
      - 8080:8080
    environment:
      GUMTREE_SCRAPER_WEBSITE-URL: "http://localhost:8080"
      SPRING_SECURITY_USER_NAME: "${ADMIN_USERNAME}"
      SPRING_SECURITY_USER_PASSWORD: "${ADMIN_PASSWORD}"
      SPRING_PROFILES_ACTIVE: web
      SPRING_DATA_MONGODB_HOST: gumtree-mongo
      SPRING_DATA_MONGODB_AUTHENTICATION-DATABASE: gumtree
      SPRING_DATA_MONGODB_USERNAME: gumtree
      SPRING_DATA_MONGODB_PASSWORD: "${ADMIN_PASSWORD}"
      # TODO: make this email dependency go away from gumtree-web (provide rest endpoint at report?)
      SPRING_MAIL_USERNAME: "${GMAIL_USERNAME}"
      SPRING_MAIL_PASSWORD: "${GMAIL_TOKEN}"

  gumtree-scraper:
    container_name: gumtree-scraper
    image: jvmops/gumtree-scraper
    restart: "no"
    depends_on:
      - gumtree-web
    environment:
      GUMTREE_SCRAPER_MAX-SCRAPPED-PAGES: 5
      SPRING_PROFILES_ACTIVE: scraper
      SPRING_MAIN_WEB-APPLICATION-TYPE: NONE
      SPRING_DATA_MONGODB_HOST: gumtree-mongo
      SPRING_DATA_MONGODB_AUTHENTICATION-DATABASE: gumtree
      SPRING_DATA_MONGODB_USERNAME: gumtree
      SPRING_DATA_MONGODB_PASSWORD: "${ADMIN_PASSWORD}"

  gumtree-report:
    container_name: gumtree-report
    image: jvmops/gumtree-scraper
    restart: "no"
    depends_on:
      - gumtree-web
    environment:
      SPRING_PROFILES_ACTIVE: report
      SPRING_MAIN_WEB-APPLICATION-TYPE: NONE
      SPRING_MAIL_USERNAME: "${GMAIL_USERNAME}"
      SPRING_MAIL_PASSWORD: "${GMAIL_TOKEN}"
      SPRING_DATA_MONGODB_HOST: gumtree-mongo
      SPRING_DATA_MONGODB_AUTHENTICATION-DATABASE: gumtree
      SPRING_DATA_MONGODB_USERNAME: gumtree
      SPRING_DATA_MONGODB_PASSWORD: "${ADMIN_PASSWORD}"
